import React, { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { Package, Wrench, Loader2, RefreshCw } from 'lucide-react';
import { Button } from '../../components/Shared';

// Advanced categorization rules generated by Gemini
const CATEGORY_RULES = [
    // --- General Surgery ---
    { keywords: ['mayo', 'metzenbaum', 'iris', 'stevens', 'tenotomy', 'lister', 'bandage', 'stitch', 'littauer', 'umbilical', 'potts-smith', 'strabismus', 'braun', 'episiotomy', 'sims', 'operating scissor', 'dissecting scissor'], category: 'General Surgery', subcategory: 'Scissors' },
    { keywords: ['adson', 'debakey', 'cushing', 'dressing', 'tissue', 'semken', 'iris forcep', 'splinter', 'hunter', 'lucae', 'jansen', 'gruenwald', 'adler', 'bonney', 'ferris', 'gerald'], category: 'General Surgery', subcategory: 'Tissue Forceps' },
    { keywords: ['hemostat', 'mosquito', 'halsted', 'kelly', 'crile', 'rochester', 'pean', 'ochsner', 'kocher', 'mixter', 'gemini', 'baby-mixter', 'overholt', 'bengolea'], category: 'General Surgery', subcategory: 'Hemostatic Forceps' },
    { keywords: ['needle holder', 'needle driver', 'mayo-hegar', 'olsen-hegar', 'mathieu', 'castroviejo', 'derf', 'webster', 'collier', 'crile-wood', 'ryder', 'wangsteen'], category: 'General Surgery', subcategory: 'Needle Holders' },
    { keywords: ['foerster', 'sponge', 'rampley', 'ballenger', 'gross', 'maier'], category: 'General Surgery', subcategory: 'Sponge Forceps' },
    { keywords: ['towel', 'backhaus', 'jones', 'schaedel', 'lorna'], category: 'General Surgery', subcategory: 'Towel Clamps' },
    { keywords: ['retractor', 'army-navy', 'army navy', 'langenbeck', 'senn', 'volkmann', 'richardson', 'kelly retractor', 'deaver', 'ribbon', 'malleable', 'rake', 'roux', 'farabeuf', 'parker', 'czerny', 'mathieu retractor', 'jackson', 'meyer', 'goelet'], category: 'General Surgery', subcategory: 'Retractors' },
    { keywords: ['self-retaining', 'weitlaner', 'gelpi', 'beckman', 'adson-beckman', 'balfour', 'gosset'], category: 'General Surgery', subcategory: 'Retractors (Self-Retaining)' },
    { keywords: ['scalpel', 'blade handle', 'bp handle', 'b.p. handle', 'knife handle'], category: 'General Surgery', subcategory: 'Scalpels & Handles' },
    { keywords: ['suction', 'poole', 'yankauer', 'frazier', 'ferguson', 'baron'], category: 'General Surgery', subcategory: 'Suction Tubes' },
    { keywords: ['probe', 'director', 'grooved director', 'malleable probe'], category: 'General Surgery', subcategory: 'Probes' },

    // --- Orthopedic ---
    { keywords: ['bone cutter', 'liston', 'ruskin', 'stille', 'bohler', 'mcreynolds'], category: 'Orthopedic', subcategory: 'Bone Cutters' },
    { keywords: ['rongeur', 'kerrison', 'beyer', 'stille-luer', 'echlin', 'lempert', 'jansen', 'luer', 'friedman', 'mead', 'csa', 'adson rongeur'], category: 'Orthopedic', subcategory: 'Rongeurs' },
    { keywords: ['osteotome', 'chisel', 'gouge', 'lambotte', 'hoke', 'hibbs', 'cobb', 'smith-petersen', 'alexander'], category: 'Orthopedic', subcategory: 'Osteotomes & Chisels' },
    { keywords: ['mallet', 'hammer', 'cottle mallet', 'mead mallet', 'lucae mallet'], category: 'Orthopedic', subcategory: 'Mallets' },
    { keywords: ['wire cutter', 'wire twister', 'pin cutter', 'bolt cutter', 'tc wire', 'k-wire'], category: 'Orthopedic', subcategory: 'Wire Instruments' },
    { keywords: ['bone clamp', 'bone holding', 'lowman', 'verbrugge', 'kern', 'lane', 'fergusson'], category: 'Orthopedic', subcategory: 'Bone Clamps' },
    { keywords: ['curette', 'volkmann', 'bruns', 'schede', 'spratt', 'daubenspeck'], category: 'Orthopedic', subcategory: 'Bone Curettes' },
    { keywords: ['elevator', 'periosteal', 'key', 'langenbeck elevator', 'adson elevator', 'freer', 'joseph', 'cobbs'], category: 'Orthopedic', subcategory: 'Periosteal Elevators' },
    { keywords: ['bone file', 'rasp', 'putti', 'aufricht', 'maltz', 'fomon'], category: 'Orthopedic', subcategory: 'Rasps & Files' },
    { keywords: ['retractor', 'bennett', 'hibbs', 'hohmann', 'blount', 'israel'], category: 'Orthopedic', subcategory: 'Orthopedic Retractors' },

    // --- Cardiovascular / Thoracic ---
    { keywords: ['vascular', 'bulldog', 'satinsky', 'debakey clamp', 'glover', 'potts', 'cooley', 'kay', 'lambert', 'lelanda'], category: 'Cardiovascular', subcategory: 'Vascular Clamps' },
    { keywords: ['rib', 'spreader', 'finochietto', 'burford', 'cooly', 'castaneda', 'haight', 'tuffier'], category: 'Cardiovascular', subcategory: 'Rib Spreaders' },
    { keywords: ['thoracic', 'lung', 'duval', 'lovelace', 'allison'], category: 'Cardiovascular', subcategory: 'Thoracic Instruments' },
    { keywords: ['stripper', 'vein'], category: 'Cardiovascular', subcategory: 'Vein Strippers' },

    // --- Neurosurgery ---
    { keywords: ['pituitary', 'cushing rongeur', 'love-gruenwald', 'caspar', 'spurling'], category: 'Neurosurgery', subcategory: 'Pituitary Rongeurs' },
    { keywords: ['laminectomy', 'kerrison', 'ferris-smith'], category: 'Neurosurgery', subcategory: 'Kerrisons' },
    { keywords: ['brain', 'spatula', 'layla', 'yasargil', 'micro scissor', 'micro forcep'], category: 'Neurosurgery', subcategory: 'Micro Instruments' },
    { keywords: ['dura', 'hook', 'nerve hook', 'dandy', 'adson hook'], category: 'Neurosurgery', subcategory: 'Nerve Hooks' },

    // --- ENT ---
    { keywords: ['speculum', 'hartman', 'farrior', 'toynbee', 'gruber', 'killian', 'vienn', 'cottle speculum'], category: 'ENT', subcategory: 'Ear & Nasal Speculums' },
    { keywords: ['forcep', 'hartman', 'noyes', 'struempel', 'tilley', 'troeltsch', 'lucae', 'jansen'], category: 'ENT', subcategory: 'Ear & Nasal Forceps' },
    { keywords: ['tonsil', 'snare', 'dissector', 'hurd', 'gwynn', 'davis', 'mcivor', 'jennings'], category: 'ENT', subcategory: 'Mouth & Throat' },
    { keywords: ['tuning fork', 'hartmann'], category: 'ENT', subcategory: 'Diagnostics' },

    // --- Dental ---
    { keywords: ['extracting', 'forceps', 'fig.', 'root', 'molar', 'biscuspid', 'incisor'], category: 'Dental', subcategory: 'Extracting Forceps' },
    { keywords: ['elevator', 'bein', 'flohr', 'cryer', 'heidbrink', 'apical'], category: 'Dental', subcategory: 'Root Elevators' },
    { keywords: ['scaler', 'explorer', 'mirror', 'college', 'meriam'], category: 'Dental', subcategory: 'Diagnostic & Periodontal' },
    { keywords: ['impression', 'tray', 'cement', 'spatula'], category: 'Dental', subcategory: 'Restorative' },

    // --- Gynecology / Obstetrics ---
    { keywords: ['speculum', 'cusco', 'graves', 'collin', 'pederson', 'sims', 'kristeller'], category: 'Gynecology', subcategory: 'Vaginal Speculums' },
    { keywords: ['uterine', 'sound', 'dilator', 'hegar', 'hank', 'goodell'], category: 'Gynecology', subcategory: 'Dilators & Sounds' },
    { keywords: ['tenaculum', 'vulsellum', 'schroeder', 'braun', 'museux', 'jacobs'], category: 'Gynecology', subcategory: 'Uterine Forceps' },
    { keywords: ['biopsy', 'punch', 'tischler', 'kevorkian', 'eppendorfer'], category: 'Gynecology', subcategory: 'Biopsy' },
    { keywords: ['obstetric', 'simpson', 'wrigley', 'elliot', 'kelland'], category: 'Gynecology', subcategory: 'Obstetric Forceps' },

    // --- Ophthalmology ---
    { keywords: ['speculum', 'barraquer', 'castroviejo speculum', 'williams'], category: 'Ophthalmology', subcategory: 'Eye Speculums' },
    { keywords: ['capsulorhexis', 'utrata', 'mcpherson', 'kelman'], category: 'Ophthalmology', subcategory: 'Forceps' },
    { keywords: ['scissor', 'vannas', 'westcott', 'castroviejo scissor'], category: 'Ophthalmology', subcategory: 'Scissors' },

    // --- Plastic Surgery ---
    { keywords: ['dermatome', 'skin graft', 'knife', 'watson', 'humby'], category: 'Plastic Surgery', subcategory: 'Dermatomes' },
    { keywords: ['hook', 'skin hook', 'joseph', 'gillies', 'frazier'], category: 'Plastic Surgery', subcategory: 'Hooks' },
    { keywords: ['breast', 'dissector', 'agriss', 'solz'], category: 'Plastic Surgery', subcategory: 'Breast Instruments' },

    // --- Urology ---
    { keywords: ['sound', 'van buren', 'guyon'], category: 'Urology', subcategory: 'Urethral Sounds' },
    { keywords: ['catheter', 'female'], category: 'Urology', subcategory: 'Catheters' },

    // --- Anaesthesia ---
    { keywords: ['laryngoscope', 'miller', 'macintosh', 'guedel', 'magill'], category: 'Anaesthesia', subcategory: 'Laryngoscopes' },

    // --- Holloware / Sterilization ---
    { keywords: ['tray', 'kidney', 'bowl', 'gallipot', 'vomit', 'urinal', 'bed pan', 'box', 'drum', 'container', 'basket', 'cassette'], category: 'Sterilization & Holloware', subcategory: 'Containers' },
    { keywords: ['jar', 'forcep jar', 'thermometer'], category: 'Sterilization & Holloware', subcategory: 'Jars' },

    // --- Diagnostic ---
    { keywords: ['hammer', 'reflex', 'taylor', 'buck', 'babinsky', 'wartenberg'], category: 'Diagnostic', subcategory: 'Reflex Hammers' },
    { keywords: ['otoscope', 'ophthalmoscope', 'diagnostic set'], category: 'Diagnostic', subcategory: 'Diagnostic Sets' },

    // --- Fallback General Matches ---
    { keywords: ['scissor'], category: 'General Surgery', subcategory: 'Scissors' },
    { keywords: ['forcep'], category: 'General Surgery', subcategory: 'Forceps' },
    { keywords: ['retractor'], category: 'General Surgery', subcategory: 'Retractors' },
    { keywords: ['needle holder'], category: 'General Surgery', subcategory: 'Needle Holders' },
    { keywords: ['clamp'], category: 'General Surgery', subcategory: 'Clamps' },
];

export const Dashboard: React.FC = () => {
    const [stats, setStats] = useState({ products: 0, uncategorized: 0 });
    const [fixing, setFixing] = useState(false);
    const [logs, setLogs] = useState<string[]>([]);

    useEffect(() => {
        fetchStats();
    }, []);

    const fetchStats = async () => {
        const { count: total } = await supabase.from('products').select('*', { count: 'exact', head: true });
        const { count: uncategorized } = await supabase.from('products').select('*', { count: 'exact', head: true }).eq('category', 'Uncategorized');
        setStats({ products: total || 0, uncategorized: uncategorized || 0 });
    };

    const addLog = (msg: string) => setLogs(prev => [msg, ...prev].slice(0, 100));

    const smartCategorize = async () => {
        setFixing(true);
        setLogs([]);
        addLog("🚀 Starting Smart Categorization...");

        try {
            // Fetch ALL products
            let allProducts: any[] = [];
            let page = 0;
            const pageSize = 1000;

            while (true) {
                const { data, error } = await supabase
                    .from('products')
                    .select('id, sku, name')
                    .range(page * pageSize, (page + 1) * pageSize - 1);

                if (error) throw error;
                if (!data || data.length === 0) break;

                allProducts = [...allProducts, ...data];
                addLog(`📥 Loaded ${allProducts.length} products...`);
                page++;
            }

            addLog(`📦 Total products to process: ${allProducts.length}`);

            let updatedCount = 0;
            let skippedCount = 0;
            const categoryStats: Record<string, number> = {};

            // Process in batches for speed
            const batchSize = 50;
            for (let i = 0; i < allProducts.length; i += batchSize) {
                const batch = allProducts.slice(i, i + batchSize);

                const updates = batch.map(product => {
                    const name = (product.name || '').toLowerCase();
                    const sku = (product.sku || '').toLowerCase();
                    const searchText = `${name} ${sku}`;

                    // Find matching rule
                    for (const rule of CATEGORY_RULES) {
                        if (rule.keywords.some(kw => searchText.includes(kw.toLowerCase()))) {
                            categoryStats[rule.category] = (categoryStats[rule.category] || 0) + 1;
                            return {
                                id: product.id,
                                category: rule.category,
                                subcategory: rule.subcategory
                            };
                        }
                    }

                    // No match - set to Uncategorized (this removes old WP categories)
                    skippedCount++;
                    return {
                        id: product.id,
                        category: 'Uncategorized',
                        subcategory: 'General'
                    };
                });

                // Batch update ALL products
                for (const update of updates) {
                    await supabase
                        .from('products')
                        .update({ category: update.category, subcategory: update.subcategory })
                        .eq('id', update.id);
                    updatedCount++;
                }

                if ((i + batchSize) % 500 === 0 || i + batchSize >= allProducts.length) {
                    addLog(`⏳ Progress: ${Math.min(i + batchSize, allProducts.length)} / ${allProducts.length}`);
                }
            }

            // Show category breakdown
            addLog(`\n📊 Category Breakdown:`);
            Object.entries(categoryStats)
                .sort((a, b) => b[1] - a[1])
                .forEach(([cat, count]) => {
                    addLog(`   ${cat}: ${count} products`);
                });

            addLog(`\n✅ Done! Categorized: ${updatedCount}, Skipped: ${skippedCount}`);
            fetchStats();

        } catch (e: any) {
            addLog(`❌ Error: ${e.message}`);
        }

        setFixing(false);
    };

    return (
        <div className="max-w-5xl mx-auto space-y-8">
            <h1 className="text-3xl font-serif text-brand-charcoal">Dashboard Overview</h1>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white p-6 rounded-xl shadow-sm border border-stone-200">
                    <div className="flex items-center gap-4 mb-4">
                        <div className="p-3 bg-blue-50 text-blue-600 rounded-lg">
                            <Package size={24} />
                        </div>
                        <div>
                            <p className="text-sm text-stone-500">Total Products</p>
                            <h3 className="text-2xl font-bold text-brand-charcoal">{stats.products}</h3>
                        </div>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-xl shadow-sm border border-stone-200">
                    <div className="flex items-center gap-4 mb-4">
                        <div className="p-3 bg-red-50 text-red-600 rounded-lg">
                            <Wrench size={24} />
                        </div>
                        <div>
                            <p className="text-sm text-stone-500">Uncategorized</p>
                            <h3 className="text-2xl font-bold text-brand-charcoal">{stats.uncategorized}</h3>
                        </div>
                    </div>
                </div>
            </div>

            {/* Smart Categorizer Tool */}
            <div className="bg-white rounded-xl shadow-sm border border-stone-200 p-8">
                <div className="flex justify-between items-center mb-6">
                    <div>
                        <h3 className="text-xl font-medium text-brand-charcoal">Smart Auto-Categorizer</h3>
                        <p className="text-sm text-stone-500">Automatically organize products using AI knowledge of surgical instruments.</p>
                    </div>
                    <Button variant="primary" onClick={smartCategorize} disabled={fixing}>
                        {fixing ? <Loader2 className="animate-spin mr-2" size={18} /> : <Wrench className="mr-2" size={18} />}
                        {fixing ? 'Processing...' : 'Run Smart Categorization'}
                    </Button>
                </div>

                <div className="mb-4 p-4 bg-blue-50 rounded-lg text-sm text-blue-800">
                    <strong>Categories:</strong> General Surgery, Orthopedic, Cardiovascular, Neurosurgery, ENT, Dental, Ophthalmology, Gynecology, Plastic Surgery, Diagnostic, Sterilization, T.C. Instruments
                </div>

                <div className="bg-stone-900 rounded-lg p-4 font-mono text-xs h-80 overflow-y-auto text-stone-300">
                    {logs.length === 0 ? "Ready to start..." : logs.map((l, i) => (
                        <div key={i} className={l.includes('❌') ? 'text-red-400' : l.includes('✅') ? 'text-green-400' : ''}>{l}</div>
                    ))}
                </div>
            </div>
        </div>
    );
};
